// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_clientmessages.proto

#ifndef PROTOBUF_dota_5fclientmessages_2eproto__INCLUDED
#define PROTOBUF_dota_5fclientmessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "google/protobuf/descriptor.pb.h"
#include "networkbasetypes.pb.h"
#include "dota_commonmessages.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();

class CDOTAClientMsg_MapPing;
class CDOTAClientMsg_ItemAlert;
class CDOTAClientMsg_MapLine;
class CDOTAClientMsg_AspectRatio;
class CDOTAClientMsg_UnitsAutoAttack;
class CDOTAClientMsg_AutoPurchaseItems;
class CDOTAClientMsg_TestItems;
class CDOTAClientMsg_SearchString;
class CDOTAClientMsg_Pause;
class CDOTAClientMsg_ShopViewMode;
class CDOTAClientMsg_SetUnitShareFlag;
class CDOTAClientMsg_SwapRequest;
class CDOTAClientMsg_SwapAccept;
class CDOTAClientMsg_WorldLine;
class CDOTAClientMsg_RequestGraphUpdate;
class CDOTAClientMsg_ChatWheel;
class CDOTAClientMsg_SendStatPopup;
class CDOTAClientMsg_BeginLastHitChallenge;

enum EDotaClientMessages {
  DOTA_CM_MapLine = 1,
  DOTA_CM_AspectRatio = 2,
  DOTA_CM_MapPing = 3,
  DOTA_CM_UnitsAutoAttack = 4,
  DOTA_CM_AutoPurchaseItems = 5,
  DOTA_CM_TestItems = 6,
  DOTA_CM_SearchString = 7,
  DOTA_CM_Pause = 8,
  DOTA_CM_ShopViewMode = 9,
  DOTA_CM_SetUnitShareFlag = 10,
  DOTA_CM_SwapRequest = 11,
  DOTA_CM_SwapAccept = 12,
  DOTA_CM_WorldLine = 13,
  DOTA_CM_RequestGraphUpdate = 14,
  DOTA_CM_ItemAlert = 15,
  DOTA_CM_ChatWheel = 16,
  DOTA_CM_SendStatPopup = 17,
  DOTA_CM_BeginLastHitChallenge = 18
};
bool EDotaClientMessages_IsValid(int value);
const EDotaClientMessages EDotaClientMessages_MIN = DOTA_CM_MapLine;
const EDotaClientMessages EDotaClientMessages_MAX = DOTA_CM_BeginLastHitChallenge;
const int EDotaClientMessages_ARRAYSIZE = EDotaClientMessages_MAX + 1;

const ::google::protobuf::EnumDescriptor* EDotaClientMessages_descriptor();
inline const ::std::string& EDotaClientMessages_Name(EDotaClientMessages value) {
  return ::google::protobuf::internal::NameOfEnum(
    EDotaClientMessages_descriptor(), value);
}
inline bool EDotaClientMessages_Parse(
    const ::std::string& name, EDotaClientMessages* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EDotaClientMessages>(
    EDotaClientMessages_descriptor(), name, value);
}
// ===================================================================

class CDOTAClientMsg_MapPing : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_MapPing();
  virtual ~CDOTAClientMsg_MapPing();
  
  CDOTAClientMsg_MapPing(const CDOTAClientMsg_MapPing& from);
  
  inline CDOTAClientMsg_MapPing& operator=(const CDOTAClientMsg_MapPing& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_MapPing& default_instance();
  
  void Swap(CDOTAClientMsg_MapPing* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_MapPing* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_MapPing& from);
  void MergeFrom(const CDOTAClientMsg_MapPing& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .CDOTAMsg_LocationPing location_ping = 1;
  inline bool has_location_ping() const;
  inline void clear_location_ping();
  static const int kLocationPingFieldNumber = 1;
  inline const ::CDOTAMsg_LocationPing& location_ping() const;
  inline ::CDOTAMsg_LocationPing* mutable_location_ping();
  inline ::CDOTAMsg_LocationPing* release_location_ping();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_MapPing)
 private:
  inline void set_has_location_ping();
  inline void clear_has_location_ping();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::CDOTAMsg_LocationPing* location_ping_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_MapPing* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_ItemAlert : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_ItemAlert();
  virtual ~CDOTAClientMsg_ItemAlert();
  
  CDOTAClientMsg_ItemAlert(const CDOTAClientMsg_ItemAlert& from);
  
  inline CDOTAClientMsg_ItemAlert& operator=(const CDOTAClientMsg_ItemAlert& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_ItemAlert& default_instance();
  
  void Swap(CDOTAClientMsg_ItemAlert* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_ItemAlert* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_ItemAlert& from);
  void MergeFrom(const CDOTAClientMsg_ItemAlert& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .CDOTAMsg_ItemAlert item_alert = 1;
  inline bool has_item_alert() const;
  inline void clear_item_alert();
  static const int kItemAlertFieldNumber = 1;
  inline const ::CDOTAMsg_ItemAlert& item_alert() const;
  inline ::CDOTAMsg_ItemAlert* mutable_item_alert();
  inline ::CDOTAMsg_ItemAlert* release_item_alert();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_ItemAlert)
 private:
  inline void set_has_item_alert();
  inline void clear_has_item_alert();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::CDOTAMsg_ItemAlert* item_alert_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_ItemAlert* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_MapLine : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_MapLine();
  virtual ~CDOTAClientMsg_MapLine();
  
  CDOTAClientMsg_MapLine(const CDOTAClientMsg_MapLine& from);
  
  inline CDOTAClientMsg_MapLine& operator=(const CDOTAClientMsg_MapLine& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_MapLine& default_instance();
  
  void Swap(CDOTAClientMsg_MapLine* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_MapLine* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_MapLine& from);
  void MergeFrom(const CDOTAClientMsg_MapLine& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .CDOTAMsg_MapLine mapline = 1;
  inline bool has_mapline() const;
  inline void clear_mapline();
  static const int kMaplineFieldNumber = 1;
  inline const ::CDOTAMsg_MapLine& mapline() const;
  inline ::CDOTAMsg_MapLine* mutable_mapline();
  inline ::CDOTAMsg_MapLine* release_mapline();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_MapLine)
 private:
  inline void set_has_mapline();
  inline void clear_has_mapline();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::CDOTAMsg_MapLine* mapline_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_MapLine* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_AspectRatio : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_AspectRatio();
  virtual ~CDOTAClientMsg_AspectRatio();
  
  CDOTAClientMsg_AspectRatio(const CDOTAClientMsg_AspectRatio& from);
  
  inline CDOTAClientMsg_AspectRatio& operator=(const CDOTAClientMsg_AspectRatio& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_AspectRatio& default_instance();
  
  void Swap(CDOTAClientMsg_AspectRatio* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_AspectRatio* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_AspectRatio& from);
  void MergeFrom(const CDOTAClientMsg_AspectRatio& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional float ratio = 1;
  inline bool has_ratio() const;
  inline void clear_ratio();
  static const int kRatioFieldNumber = 1;
  inline float ratio() const;
  inline void set_ratio(float value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_AspectRatio)
 private:
  inline void set_has_ratio();
  inline void clear_has_ratio();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float ratio_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_AspectRatio* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_UnitsAutoAttack : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_UnitsAutoAttack();
  virtual ~CDOTAClientMsg_UnitsAutoAttack();
  
  CDOTAClientMsg_UnitsAutoAttack(const CDOTAClientMsg_UnitsAutoAttack& from);
  
  inline CDOTAClientMsg_UnitsAutoAttack& operator=(const CDOTAClientMsg_UnitsAutoAttack& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_UnitsAutoAttack& default_instance();
  
  void Swap(CDOTAClientMsg_UnitsAutoAttack* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_UnitsAutoAttack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_UnitsAutoAttack& from);
  void MergeFrom(const CDOTAClientMsg_UnitsAutoAttack& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool enabled = 1;
  inline bool has_enabled() const;
  inline void clear_enabled();
  static const int kEnabledFieldNumber = 1;
  inline bool enabled() const;
  inline void set_enabled(bool value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_UnitsAutoAttack)
 private:
  inline void set_has_enabled();
  inline void clear_has_enabled();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  bool enabled_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_UnitsAutoAttack* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_AutoPurchaseItems : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_AutoPurchaseItems();
  virtual ~CDOTAClientMsg_AutoPurchaseItems();
  
  CDOTAClientMsg_AutoPurchaseItems(const CDOTAClientMsg_AutoPurchaseItems& from);
  
  inline CDOTAClientMsg_AutoPurchaseItems& operator=(const CDOTAClientMsg_AutoPurchaseItems& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_AutoPurchaseItems& default_instance();
  
  void Swap(CDOTAClientMsg_AutoPurchaseItems* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_AutoPurchaseItems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_AutoPurchaseItems& from);
  void MergeFrom(const CDOTAClientMsg_AutoPurchaseItems& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool enabled = 1;
  inline bool has_enabled() const;
  inline void clear_enabled();
  static const int kEnabledFieldNumber = 1;
  inline bool enabled() const;
  inline void set_enabled(bool value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_AutoPurchaseItems)
 private:
  inline void set_has_enabled();
  inline void clear_has_enabled();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  bool enabled_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_AutoPurchaseItems* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_TestItems : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_TestItems();
  virtual ~CDOTAClientMsg_TestItems();
  
  CDOTAClientMsg_TestItems(const CDOTAClientMsg_TestItems& from);
  
  inline CDOTAClientMsg_TestItems& operator=(const CDOTAClientMsg_TestItems& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_TestItems& default_instance();
  
  void Swap(CDOTAClientMsg_TestItems* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_TestItems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_TestItems& from);
  void MergeFrom(const CDOTAClientMsg_TestItems& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string key_values = 1;
  inline bool has_key_values() const;
  inline void clear_key_values();
  static const int kKeyValuesFieldNumber = 1;
  inline const ::std::string& key_values() const;
  inline void set_key_values(const ::std::string& value);
  inline void set_key_values(const char* value);
  inline void set_key_values(const char* value, size_t size);
  inline ::std::string* mutable_key_values();
  inline ::std::string* release_key_values();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_TestItems)
 private:
  inline void set_has_key_values();
  inline void clear_has_key_values();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* key_values_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_TestItems* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_SearchString : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_SearchString();
  virtual ~CDOTAClientMsg_SearchString();
  
  CDOTAClientMsg_SearchString(const CDOTAClientMsg_SearchString& from);
  
  inline CDOTAClientMsg_SearchString& operator=(const CDOTAClientMsg_SearchString& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_SearchString& default_instance();
  
  void Swap(CDOTAClientMsg_SearchString* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_SearchString* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_SearchString& from);
  void MergeFrom(const CDOTAClientMsg_SearchString& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string search = 1;
  inline bool has_search() const;
  inline void clear_search();
  static const int kSearchFieldNumber = 1;
  inline const ::std::string& search() const;
  inline void set_search(const ::std::string& value);
  inline void set_search(const char* value);
  inline void set_search(const char* value, size_t size);
  inline ::std::string* mutable_search();
  inline ::std::string* release_search();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_SearchString)
 private:
  inline void set_has_search();
  inline void clear_has_search();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* search_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_SearchString* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_Pause : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_Pause();
  virtual ~CDOTAClientMsg_Pause();
  
  CDOTAClientMsg_Pause(const CDOTAClientMsg_Pause& from);
  
  inline CDOTAClientMsg_Pause& operator=(const CDOTAClientMsg_Pause& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_Pause& default_instance();
  
  void Swap(CDOTAClientMsg_Pause* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_Pause* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_Pause& from);
  void MergeFrom(const CDOTAClientMsg_Pause& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_Pause)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_Pause* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_ShopViewMode : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_ShopViewMode();
  virtual ~CDOTAClientMsg_ShopViewMode();
  
  CDOTAClientMsg_ShopViewMode(const CDOTAClientMsg_ShopViewMode& from);
  
  inline CDOTAClientMsg_ShopViewMode& operator=(const CDOTAClientMsg_ShopViewMode& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_ShopViewMode& default_instance();
  
  void Swap(CDOTAClientMsg_ShopViewMode* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_ShopViewMode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_ShopViewMode& from);
  void MergeFrom(const CDOTAClientMsg_ShopViewMode& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 mode = 1;
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 1;
  inline ::google::protobuf::uint32 mode() const;
  inline void set_mode(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_ShopViewMode)
 private:
  inline void set_has_mode();
  inline void clear_has_mode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 mode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_ShopViewMode* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_SetUnitShareFlag : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_SetUnitShareFlag();
  virtual ~CDOTAClientMsg_SetUnitShareFlag();
  
  CDOTAClientMsg_SetUnitShareFlag(const CDOTAClientMsg_SetUnitShareFlag& from);
  
  inline CDOTAClientMsg_SetUnitShareFlag& operator=(const CDOTAClientMsg_SetUnitShareFlag& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_SetUnitShareFlag& default_instance();
  
  void Swap(CDOTAClientMsg_SetUnitShareFlag* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_SetUnitShareFlag* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_SetUnitShareFlag& from);
  void MergeFrom(const CDOTAClientMsg_SetUnitShareFlag& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 playerID = 1;
  inline bool has_playerid() const;
  inline void clear_playerid();
  static const int kPlayerIDFieldNumber = 1;
  inline ::google::protobuf::uint32 playerid() const;
  inline void set_playerid(::google::protobuf::uint32 value);
  
  // optional uint32 flag = 2;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 2;
  inline ::google::protobuf::uint32 flag() const;
  inline void set_flag(::google::protobuf::uint32 value);
  
  // optional bool state = 3;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 3;
  inline bool state() const;
  inline void set_state(bool value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_SetUnitShareFlag)
 private:
  inline void set_has_playerid();
  inline void clear_has_playerid();
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_state();
  inline void clear_has_state();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 playerid_;
  ::google::protobuf::uint32 flag_;
  bool state_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_SetUnitShareFlag* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_SwapRequest : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_SwapRequest();
  virtual ~CDOTAClientMsg_SwapRequest();
  
  CDOTAClientMsg_SwapRequest(const CDOTAClientMsg_SwapRequest& from);
  
  inline CDOTAClientMsg_SwapRequest& operator=(const CDOTAClientMsg_SwapRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_SwapRequest& default_instance();
  
  void Swap(CDOTAClientMsg_SwapRequest* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_SwapRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_SwapRequest& from);
  void MergeFrom(const CDOTAClientMsg_SwapRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::uint32 player_id() const;
  inline void set_player_id(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_SwapRequest)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 player_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_SwapRequest* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_SwapAccept : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_SwapAccept();
  virtual ~CDOTAClientMsg_SwapAccept();
  
  CDOTAClientMsg_SwapAccept(const CDOTAClientMsg_SwapAccept& from);
  
  inline CDOTAClientMsg_SwapAccept& operator=(const CDOTAClientMsg_SwapAccept& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_SwapAccept& default_instance();
  
  void Swap(CDOTAClientMsg_SwapAccept* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_SwapAccept* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_SwapAccept& from);
  void MergeFrom(const CDOTAClientMsg_SwapAccept& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::uint32 player_id() const;
  inline void set_player_id(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_SwapAccept)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 player_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_SwapAccept* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_WorldLine : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_WorldLine();
  virtual ~CDOTAClientMsg_WorldLine();
  
  CDOTAClientMsg_WorldLine(const CDOTAClientMsg_WorldLine& from);
  
  inline CDOTAClientMsg_WorldLine& operator=(const CDOTAClientMsg_WorldLine& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_WorldLine& default_instance();
  
  void Swap(CDOTAClientMsg_WorldLine* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_WorldLine* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_WorldLine& from);
  void MergeFrom(const CDOTAClientMsg_WorldLine& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .CDOTAMsg_WorldLine worldline = 1;
  inline bool has_worldline() const;
  inline void clear_worldline();
  static const int kWorldlineFieldNumber = 1;
  inline const ::CDOTAMsg_WorldLine& worldline() const;
  inline ::CDOTAMsg_WorldLine* mutable_worldline();
  inline ::CDOTAMsg_WorldLine* release_worldline();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_WorldLine)
 private:
  inline void set_has_worldline();
  inline void clear_has_worldline();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::CDOTAMsg_WorldLine* worldline_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_WorldLine* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_RequestGraphUpdate : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_RequestGraphUpdate();
  virtual ~CDOTAClientMsg_RequestGraphUpdate();
  
  CDOTAClientMsg_RequestGraphUpdate(const CDOTAClientMsg_RequestGraphUpdate& from);
  
  inline CDOTAClientMsg_RequestGraphUpdate& operator=(const CDOTAClientMsg_RequestGraphUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_RequestGraphUpdate& default_instance();
  
  void Swap(CDOTAClientMsg_RequestGraphUpdate* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_RequestGraphUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_RequestGraphUpdate& from);
  void MergeFrom(const CDOTAClientMsg_RequestGraphUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_RequestGraphUpdate)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_RequestGraphUpdate* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_ChatWheel : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_ChatWheel();
  virtual ~CDOTAClientMsg_ChatWheel();
  
  CDOTAClientMsg_ChatWheel(const CDOTAClientMsg_ChatWheel& from);
  
  inline CDOTAClientMsg_ChatWheel& operator=(const CDOTAClientMsg_ChatWheel& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_ChatWheel& default_instance();
  
  void Swap(CDOTAClientMsg_ChatWheel* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_ChatWheel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_ChatWheel& from);
  void MergeFrom(const CDOTAClientMsg_ChatWheel& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .EDOTAChatWheelMessage chat_message = 1 [default = k_EDOTA_CW_Ok];
  inline bool has_chat_message() const;
  inline void clear_chat_message();
  static const int kChatMessageFieldNumber = 1;
  inline EDOTAChatWheelMessage chat_message() const;
  inline void set_chat_message(EDOTAChatWheelMessage value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_ChatWheel)
 private:
  inline void set_has_chat_message();
  inline void clear_has_chat_message();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  int chat_message_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_ChatWheel* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_SendStatPopup : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_SendStatPopup();
  virtual ~CDOTAClientMsg_SendStatPopup();
  
  CDOTAClientMsg_SendStatPopup(const CDOTAClientMsg_SendStatPopup& from);
  
  inline CDOTAClientMsg_SendStatPopup& operator=(const CDOTAClientMsg_SendStatPopup& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_SendStatPopup& default_instance();
  
  void Swap(CDOTAClientMsg_SendStatPopup* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_SendStatPopup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_SendStatPopup& from);
  void MergeFrom(const CDOTAClientMsg_SendStatPopup& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .CDOTAMsg_SendStatPopup statpopup = 1;
  inline bool has_statpopup() const;
  inline void clear_statpopup();
  static const int kStatpopupFieldNumber = 1;
  inline const ::CDOTAMsg_SendStatPopup& statpopup() const;
  inline ::CDOTAMsg_SendStatPopup* mutable_statpopup();
  inline ::CDOTAMsg_SendStatPopup* release_statpopup();
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_SendStatPopup)
 private:
  inline void set_has_statpopup();
  inline void clear_has_statpopup();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::CDOTAMsg_SendStatPopup* statpopup_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_SendStatPopup* default_instance_;
};
// -------------------------------------------------------------------

class CDOTAClientMsg_BeginLastHitChallenge : public ::google::protobuf::Message {
 public:
  CDOTAClientMsg_BeginLastHitChallenge();
  virtual ~CDOTAClientMsg_BeginLastHitChallenge();
  
  CDOTAClientMsg_BeginLastHitChallenge(const CDOTAClientMsg_BeginLastHitChallenge& from);
  
  inline CDOTAClientMsg_BeginLastHitChallenge& operator=(const CDOTAClientMsg_BeginLastHitChallenge& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CDOTAClientMsg_BeginLastHitChallenge& default_instance();
  
  void Swap(CDOTAClientMsg_BeginLastHitChallenge* other);
  
  // implements Message ----------------------------------------------
  
  CDOTAClientMsg_BeginLastHitChallenge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CDOTAClientMsg_BeginLastHitChallenge& from);
  void MergeFrom(const CDOTAClientMsg_BeginLastHitChallenge& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 chosen_lane = 1;
  inline bool has_chosen_lane() const;
  inline void clear_chosen_lane();
  static const int kChosenLaneFieldNumber = 1;
  inline ::google::protobuf::uint32 chosen_lane() const;
  inline void set_chosen_lane(::google::protobuf::uint32 value);
  
  // optional bool helper_enabled = 2;
  inline bool has_helper_enabled() const;
  inline void clear_helper_enabled();
  static const int kHelperEnabledFieldNumber = 2;
  inline bool helper_enabled() const;
  inline void set_helper_enabled(bool value);
  
  // @@protoc_insertion_point(class_scope:CDOTAClientMsg_BeginLastHitChallenge)
 private:
  inline void set_has_chosen_lane();
  inline void clear_has_chosen_lane();
  inline void set_has_helper_enabled();
  inline void clear_has_helper_enabled();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 chosen_lane_;
  bool helper_enabled_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_AssignDesc_dota_5fclientmessages_2eproto();
  friend void protobuf_ShutdownFile_dota_5fclientmessages_2eproto();
  
  void InitAsDefaultInstance();
  static CDOTAClientMsg_BeginLastHitChallenge* default_instance_;
};
// ===================================================================


// ===================================================================

// CDOTAClientMsg_MapPing

// optional .CDOTAMsg_LocationPing location_ping = 1;
inline bool CDOTAClientMsg_MapPing::has_location_ping() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_MapPing::set_has_location_ping() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_MapPing::clear_has_location_ping() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_MapPing::clear_location_ping() {
  if (location_ping_ != NULL) location_ping_->::CDOTAMsg_LocationPing::Clear();
  clear_has_location_ping();
}
inline const ::CDOTAMsg_LocationPing& CDOTAClientMsg_MapPing::location_ping() const {
  return location_ping_ != NULL ? *location_ping_ : *default_instance_->location_ping_;
}
inline ::CDOTAMsg_LocationPing* CDOTAClientMsg_MapPing::mutable_location_ping() {
  set_has_location_ping();
  if (location_ping_ == NULL) location_ping_ = new ::CDOTAMsg_LocationPing;
  return location_ping_;
}
inline ::CDOTAMsg_LocationPing* CDOTAClientMsg_MapPing::release_location_ping() {
  clear_has_location_ping();
  ::CDOTAMsg_LocationPing* temp = location_ping_;
  location_ping_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_ItemAlert

// optional .CDOTAMsg_ItemAlert item_alert = 1;
inline bool CDOTAClientMsg_ItemAlert::has_item_alert() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_ItemAlert::set_has_item_alert() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_ItemAlert::clear_has_item_alert() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_ItemAlert::clear_item_alert() {
  if (item_alert_ != NULL) item_alert_->::CDOTAMsg_ItemAlert::Clear();
  clear_has_item_alert();
}
inline const ::CDOTAMsg_ItemAlert& CDOTAClientMsg_ItemAlert::item_alert() const {
  return item_alert_ != NULL ? *item_alert_ : *default_instance_->item_alert_;
}
inline ::CDOTAMsg_ItemAlert* CDOTAClientMsg_ItemAlert::mutable_item_alert() {
  set_has_item_alert();
  if (item_alert_ == NULL) item_alert_ = new ::CDOTAMsg_ItemAlert;
  return item_alert_;
}
inline ::CDOTAMsg_ItemAlert* CDOTAClientMsg_ItemAlert::release_item_alert() {
  clear_has_item_alert();
  ::CDOTAMsg_ItemAlert* temp = item_alert_;
  item_alert_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_MapLine

// optional .CDOTAMsg_MapLine mapline = 1;
inline bool CDOTAClientMsg_MapLine::has_mapline() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_MapLine::set_has_mapline() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_MapLine::clear_has_mapline() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_MapLine::clear_mapline() {
  if (mapline_ != NULL) mapline_->::CDOTAMsg_MapLine::Clear();
  clear_has_mapline();
}
inline const ::CDOTAMsg_MapLine& CDOTAClientMsg_MapLine::mapline() const {
  return mapline_ != NULL ? *mapline_ : *default_instance_->mapline_;
}
inline ::CDOTAMsg_MapLine* CDOTAClientMsg_MapLine::mutable_mapline() {
  set_has_mapline();
  if (mapline_ == NULL) mapline_ = new ::CDOTAMsg_MapLine;
  return mapline_;
}
inline ::CDOTAMsg_MapLine* CDOTAClientMsg_MapLine::release_mapline() {
  clear_has_mapline();
  ::CDOTAMsg_MapLine* temp = mapline_;
  mapline_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_AspectRatio

// optional float ratio = 1;
inline bool CDOTAClientMsg_AspectRatio::has_ratio() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_AspectRatio::set_has_ratio() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_AspectRatio::clear_has_ratio() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_AspectRatio::clear_ratio() {
  ratio_ = 0;
  clear_has_ratio();
}
inline float CDOTAClientMsg_AspectRatio::ratio() const {
  return ratio_;
}
inline void CDOTAClientMsg_AspectRatio::set_ratio(float value) {
  set_has_ratio();
  ratio_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_UnitsAutoAttack

// optional bool enabled = 1;
inline bool CDOTAClientMsg_UnitsAutoAttack::has_enabled() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_UnitsAutoAttack::set_has_enabled() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_UnitsAutoAttack::clear_has_enabled() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_UnitsAutoAttack::clear_enabled() {
  enabled_ = false;
  clear_has_enabled();
}
inline bool CDOTAClientMsg_UnitsAutoAttack::enabled() const {
  return enabled_;
}
inline void CDOTAClientMsg_UnitsAutoAttack::set_enabled(bool value) {
  set_has_enabled();
  enabled_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_AutoPurchaseItems

// optional bool enabled = 1;
inline bool CDOTAClientMsg_AutoPurchaseItems::has_enabled() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_AutoPurchaseItems::set_has_enabled() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_AutoPurchaseItems::clear_has_enabled() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_AutoPurchaseItems::clear_enabled() {
  enabled_ = false;
  clear_has_enabled();
}
inline bool CDOTAClientMsg_AutoPurchaseItems::enabled() const {
  return enabled_;
}
inline void CDOTAClientMsg_AutoPurchaseItems::set_enabled(bool value) {
  set_has_enabled();
  enabled_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_TestItems

// optional string key_values = 1;
inline bool CDOTAClientMsg_TestItems::has_key_values() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_TestItems::set_has_key_values() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_TestItems::clear_has_key_values() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_TestItems::clear_key_values() {
  if (key_values_ != &::google::protobuf::internal::kEmptyString) {
    key_values_->clear();
  }
  clear_has_key_values();
}
inline const ::std::string& CDOTAClientMsg_TestItems::key_values() const {
  return *key_values_;
}
inline void CDOTAClientMsg_TestItems::set_key_values(const ::std::string& value) {
  set_has_key_values();
  if (key_values_ == &::google::protobuf::internal::kEmptyString) {
    key_values_ = new ::std::string;
  }
  key_values_->assign(value);
}
inline void CDOTAClientMsg_TestItems::set_key_values(const char* value) {
  set_has_key_values();
  if (key_values_ == &::google::protobuf::internal::kEmptyString) {
    key_values_ = new ::std::string;
  }
  key_values_->assign(value);
}
inline void CDOTAClientMsg_TestItems::set_key_values(const char* value, size_t size) {
  set_has_key_values();
  if (key_values_ == &::google::protobuf::internal::kEmptyString) {
    key_values_ = new ::std::string;
  }
  key_values_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CDOTAClientMsg_TestItems::mutable_key_values() {
  set_has_key_values();
  if (key_values_ == &::google::protobuf::internal::kEmptyString) {
    key_values_ = new ::std::string;
  }
  return key_values_;
}
inline ::std::string* CDOTAClientMsg_TestItems::release_key_values() {
  clear_has_key_values();
  if (key_values_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_values_;
    key_values_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// CDOTAClientMsg_SearchString

// optional string search = 1;
inline bool CDOTAClientMsg_SearchString::has_search() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_SearchString::set_has_search() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_SearchString::clear_has_search() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_SearchString::clear_search() {
  if (search_ != &::google::protobuf::internal::kEmptyString) {
    search_->clear();
  }
  clear_has_search();
}
inline const ::std::string& CDOTAClientMsg_SearchString::search() const {
  return *search_;
}
inline void CDOTAClientMsg_SearchString::set_search(const ::std::string& value) {
  set_has_search();
  if (search_ == &::google::protobuf::internal::kEmptyString) {
    search_ = new ::std::string;
  }
  search_->assign(value);
}
inline void CDOTAClientMsg_SearchString::set_search(const char* value) {
  set_has_search();
  if (search_ == &::google::protobuf::internal::kEmptyString) {
    search_ = new ::std::string;
  }
  search_->assign(value);
}
inline void CDOTAClientMsg_SearchString::set_search(const char* value, size_t size) {
  set_has_search();
  if (search_ == &::google::protobuf::internal::kEmptyString) {
    search_ = new ::std::string;
  }
  search_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CDOTAClientMsg_SearchString::mutable_search() {
  set_has_search();
  if (search_ == &::google::protobuf::internal::kEmptyString) {
    search_ = new ::std::string;
  }
  return search_;
}
inline ::std::string* CDOTAClientMsg_SearchString::release_search() {
  clear_has_search();
  if (search_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = search_;
    search_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// CDOTAClientMsg_Pause

// -------------------------------------------------------------------

// CDOTAClientMsg_ShopViewMode

// optional uint32 mode = 1;
inline bool CDOTAClientMsg_ShopViewMode::has_mode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_ShopViewMode::set_has_mode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_ShopViewMode::clear_has_mode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_ShopViewMode::clear_mode() {
  mode_ = 0u;
  clear_has_mode();
}
inline ::google::protobuf::uint32 CDOTAClientMsg_ShopViewMode::mode() const {
  return mode_;
}
inline void CDOTAClientMsg_ShopViewMode::set_mode(::google::protobuf::uint32 value) {
  set_has_mode();
  mode_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_SetUnitShareFlag

// optional uint32 playerID = 1;
inline bool CDOTAClientMsg_SetUnitShareFlag::has_playerid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_SetUnitShareFlag::set_has_playerid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_SetUnitShareFlag::clear_has_playerid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_SetUnitShareFlag::clear_playerid() {
  playerid_ = 0u;
  clear_has_playerid();
}
inline ::google::protobuf::uint32 CDOTAClientMsg_SetUnitShareFlag::playerid() const {
  return playerid_;
}
inline void CDOTAClientMsg_SetUnitShareFlag::set_playerid(::google::protobuf::uint32 value) {
  set_has_playerid();
  playerid_ = value;
}

// optional uint32 flag = 2;
inline bool CDOTAClientMsg_SetUnitShareFlag::has_flag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CDOTAClientMsg_SetUnitShareFlag::set_has_flag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CDOTAClientMsg_SetUnitShareFlag::clear_has_flag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CDOTAClientMsg_SetUnitShareFlag::clear_flag() {
  flag_ = 0u;
  clear_has_flag();
}
inline ::google::protobuf::uint32 CDOTAClientMsg_SetUnitShareFlag::flag() const {
  return flag_;
}
inline void CDOTAClientMsg_SetUnitShareFlag::set_flag(::google::protobuf::uint32 value) {
  set_has_flag();
  flag_ = value;
}

// optional bool state = 3;
inline bool CDOTAClientMsg_SetUnitShareFlag::has_state() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CDOTAClientMsg_SetUnitShareFlag::set_has_state() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CDOTAClientMsg_SetUnitShareFlag::clear_has_state() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CDOTAClientMsg_SetUnitShareFlag::clear_state() {
  state_ = false;
  clear_has_state();
}
inline bool CDOTAClientMsg_SetUnitShareFlag::state() const {
  return state_;
}
inline void CDOTAClientMsg_SetUnitShareFlag::set_state(bool value) {
  set_has_state();
  state_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_SwapRequest

// optional uint32 player_id = 1;
inline bool CDOTAClientMsg_SwapRequest::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_SwapRequest::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_SwapRequest::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_SwapRequest::clear_player_id() {
  player_id_ = 0u;
  clear_has_player_id();
}
inline ::google::protobuf::uint32 CDOTAClientMsg_SwapRequest::player_id() const {
  return player_id_;
}
inline void CDOTAClientMsg_SwapRequest::set_player_id(::google::protobuf::uint32 value) {
  set_has_player_id();
  player_id_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_SwapAccept

// optional uint32 player_id = 1;
inline bool CDOTAClientMsg_SwapAccept::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_SwapAccept::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_SwapAccept::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_SwapAccept::clear_player_id() {
  player_id_ = 0u;
  clear_has_player_id();
}
inline ::google::protobuf::uint32 CDOTAClientMsg_SwapAccept::player_id() const {
  return player_id_;
}
inline void CDOTAClientMsg_SwapAccept::set_player_id(::google::protobuf::uint32 value) {
  set_has_player_id();
  player_id_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_WorldLine

// optional .CDOTAMsg_WorldLine worldline = 1;
inline bool CDOTAClientMsg_WorldLine::has_worldline() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_WorldLine::set_has_worldline() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_WorldLine::clear_has_worldline() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_WorldLine::clear_worldline() {
  if (worldline_ != NULL) worldline_->::CDOTAMsg_WorldLine::Clear();
  clear_has_worldline();
}
inline const ::CDOTAMsg_WorldLine& CDOTAClientMsg_WorldLine::worldline() const {
  return worldline_ != NULL ? *worldline_ : *default_instance_->worldline_;
}
inline ::CDOTAMsg_WorldLine* CDOTAClientMsg_WorldLine::mutable_worldline() {
  set_has_worldline();
  if (worldline_ == NULL) worldline_ = new ::CDOTAMsg_WorldLine;
  return worldline_;
}
inline ::CDOTAMsg_WorldLine* CDOTAClientMsg_WorldLine::release_worldline() {
  clear_has_worldline();
  ::CDOTAMsg_WorldLine* temp = worldline_;
  worldline_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_RequestGraphUpdate

// -------------------------------------------------------------------

// CDOTAClientMsg_ChatWheel

// optional .EDOTAChatWheelMessage chat_message = 1 [default = k_EDOTA_CW_Ok];
inline bool CDOTAClientMsg_ChatWheel::has_chat_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_ChatWheel::set_has_chat_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_ChatWheel::clear_has_chat_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_ChatWheel::clear_chat_message() {
  chat_message_ = 0;
  clear_has_chat_message();
}
inline EDOTAChatWheelMessage CDOTAClientMsg_ChatWheel::chat_message() const {
  return static_cast< EDOTAChatWheelMessage >(chat_message_);
}
inline void CDOTAClientMsg_ChatWheel::set_chat_message(EDOTAChatWheelMessage value) {
  GOOGLE_DCHECK(EDOTAChatWheelMessage_IsValid(value));
  set_has_chat_message();
  chat_message_ = value;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_SendStatPopup

// optional .CDOTAMsg_SendStatPopup statpopup = 1;
inline bool CDOTAClientMsg_SendStatPopup::has_statpopup() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_SendStatPopup::set_has_statpopup() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_SendStatPopup::clear_has_statpopup() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_SendStatPopup::clear_statpopup() {
  if (statpopup_ != NULL) statpopup_->::CDOTAMsg_SendStatPopup::Clear();
  clear_has_statpopup();
}
inline const ::CDOTAMsg_SendStatPopup& CDOTAClientMsg_SendStatPopup::statpopup() const {
  return statpopup_ != NULL ? *statpopup_ : *default_instance_->statpopup_;
}
inline ::CDOTAMsg_SendStatPopup* CDOTAClientMsg_SendStatPopup::mutable_statpopup() {
  set_has_statpopup();
  if (statpopup_ == NULL) statpopup_ = new ::CDOTAMsg_SendStatPopup;
  return statpopup_;
}
inline ::CDOTAMsg_SendStatPopup* CDOTAClientMsg_SendStatPopup::release_statpopup() {
  clear_has_statpopup();
  ::CDOTAMsg_SendStatPopup* temp = statpopup_;
  statpopup_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// CDOTAClientMsg_BeginLastHitChallenge

// optional uint32 chosen_lane = 1;
inline bool CDOTAClientMsg_BeginLastHitChallenge::has_chosen_lane() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::set_has_chosen_lane() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::clear_has_chosen_lane() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::clear_chosen_lane() {
  chosen_lane_ = 0u;
  clear_has_chosen_lane();
}
inline ::google::protobuf::uint32 CDOTAClientMsg_BeginLastHitChallenge::chosen_lane() const {
  return chosen_lane_;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::set_chosen_lane(::google::protobuf::uint32 value) {
  set_has_chosen_lane();
  chosen_lane_ = value;
}

// optional bool helper_enabled = 2;
inline bool CDOTAClientMsg_BeginLastHitChallenge::has_helper_enabled() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::set_has_helper_enabled() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::clear_has_helper_enabled() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::clear_helper_enabled() {
  helper_enabled_ = false;
  clear_has_helper_enabled();
}
inline bool CDOTAClientMsg_BeginLastHitChallenge::helper_enabled() const {
  return helper_enabled_;
}
inline void CDOTAClientMsg_BeginLastHitChallenge::set_helper_enabled(bool value) {
  set_has_helper_enabled();
  helper_enabled_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< EDotaClientMessages>() {
  return EDotaClientMessages_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dota_5fclientmessages_2eproto__INCLUDED
