// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine_gcmessages.proto

#ifndef PROTOBUF_engine_5fgcmessages_2eproto__INCLUDED
#define PROTOBUF_engine_5fgcmessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
class CEngineGotvSyncPacket;
class CEngineGotvSyncPacketDefaultTypeInternal;
extern CEngineGotvSyncPacketDefaultTypeInternal _CEngineGotvSyncPacket_default_instance_;
namespace google {
namespace protobuf {
class DescriptorProto;
class DescriptorProtoDefaultTypeInternal;
extern DescriptorProtoDefaultTypeInternal _DescriptorProto_default_instance_;
class DescriptorProto_ExtensionRange;
class DescriptorProto_ExtensionRangeDefaultTypeInternal;
extern DescriptorProto_ExtensionRangeDefaultTypeInternal _DescriptorProto_ExtensionRange_default_instance_;
class DescriptorProto_ReservedRange;
class DescriptorProto_ReservedRangeDefaultTypeInternal;
extern DescriptorProto_ReservedRangeDefaultTypeInternal _DescriptorProto_ReservedRange_default_instance_;
class EnumDescriptorProto;
class EnumDescriptorProtoDefaultTypeInternal;
extern EnumDescriptorProtoDefaultTypeInternal _EnumDescriptorProto_default_instance_;
class EnumOptions;
class EnumOptionsDefaultTypeInternal;
extern EnumOptionsDefaultTypeInternal _EnumOptions_default_instance_;
class EnumValueDescriptorProto;
class EnumValueDescriptorProtoDefaultTypeInternal;
extern EnumValueDescriptorProtoDefaultTypeInternal _EnumValueDescriptorProto_default_instance_;
class EnumValueOptions;
class EnumValueOptionsDefaultTypeInternal;
extern EnumValueOptionsDefaultTypeInternal _EnumValueOptions_default_instance_;
class FieldDescriptorProto;
class FieldDescriptorProtoDefaultTypeInternal;
extern FieldDescriptorProtoDefaultTypeInternal _FieldDescriptorProto_default_instance_;
class FieldOptions;
class FieldOptionsDefaultTypeInternal;
extern FieldOptionsDefaultTypeInternal _FieldOptions_default_instance_;
class FileDescriptorProto;
class FileDescriptorProtoDefaultTypeInternal;
extern FileDescriptorProtoDefaultTypeInternal _FileDescriptorProto_default_instance_;
class FileDescriptorSet;
class FileDescriptorSetDefaultTypeInternal;
extern FileDescriptorSetDefaultTypeInternal _FileDescriptorSet_default_instance_;
class FileOptions;
class FileOptionsDefaultTypeInternal;
extern FileOptionsDefaultTypeInternal _FileOptions_default_instance_;
class GeneratedCodeInfo;
class GeneratedCodeInfoDefaultTypeInternal;
extern GeneratedCodeInfoDefaultTypeInternal _GeneratedCodeInfo_default_instance_;
class GeneratedCodeInfo_Annotation;
class GeneratedCodeInfo_AnnotationDefaultTypeInternal;
extern GeneratedCodeInfo_AnnotationDefaultTypeInternal _GeneratedCodeInfo_Annotation_default_instance_;
class MessageOptions;
class MessageOptionsDefaultTypeInternal;
extern MessageOptionsDefaultTypeInternal _MessageOptions_default_instance_;
class MethodDescriptorProto;
class MethodDescriptorProtoDefaultTypeInternal;
extern MethodDescriptorProtoDefaultTypeInternal _MethodDescriptorProto_default_instance_;
class MethodOptions;
class MethodOptionsDefaultTypeInternal;
extern MethodOptionsDefaultTypeInternal _MethodOptions_default_instance_;
class OneofDescriptorProto;
class OneofDescriptorProtoDefaultTypeInternal;
extern OneofDescriptorProtoDefaultTypeInternal _OneofDescriptorProto_default_instance_;
class OneofOptions;
class OneofOptionsDefaultTypeInternal;
extern OneofOptionsDefaultTypeInternal _OneofOptions_default_instance_;
class ServiceDescriptorProto;
class ServiceDescriptorProtoDefaultTypeInternal;
extern ServiceDescriptorProtoDefaultTypeInternal _ServiceDescriptorProto_default_instance_;
class ServiceOptions;
class ServiceOptionsDefaultTypeInternal;
extern ServiceOptionsDefaultTypeInternal _ServiceOptions_default_instance_;
class SourceCodeInfo;
class SourceCodeInfoDefaultTypeInternal;
extern SourceCodeInfoDefaultTypeInternal _SourceCodeInfo_default_instance_;
class SourceCodeInfo_Location;
class SourceCodeInfo_LocationDefaultTypeInternal;
extern SourceCodeInfo_LocationDefaultTypeInternal _SourceCodeInfo_Location_default_instance_;
class UninterpretedOption;
class UninterpretedOptionDefaultTypeInternal;
extern UninterpretedOptionDefaultTypeInternal _UninterpretedOption_default_instance_;
class UninterpretedOption_NamePart;
class UninterpretedOption_NamePartDefaultTypeInternal;
extern UninterpretedOption_NamePartDefaultTypeInternal _UninterpretedOption_NamePart_default_instance_;
}  // namespace protobuf
}  // namespace google

namespace protobuf_engine_5fgcmessages_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_engine_5fgcmessages_2eproto

// ===================================================================

class CEngineGotvSyncPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CEngineGotvSyncPacket) */ {
 public:
  CEngineGotvSyncPacket();
  virtual ~CEngineGotvSyncPacket();

  CEngineGotvSyncPacket(const CEngineGotvSyncPacket& from);

  inline CEngineGotvSyncPacket& operator=(const CEngineGotvSyncPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CEngineGotvSyncPacket& default_instance();

  static inline const CEngineGotvSyncPacket* internal_default_instance() {
    return reinterpret_cast<const CEngineGotvSyncPacket*>(
               &_CEngineGotvSyncPacket_default_instance_);
  }

  void Swap(CEngineGotvSyncPacket* other);

  // implements Message ----------------------------------------------

  inline CEngineGotvSyncPacket* New() const PROTOBUF_FINAL { return New(NULL); }

  CEngineGotvSyncPacket* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CEngineGotvSyncPacket& from);
  void MergeFrom(const CEngineGotvSyncPacket& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CEngineGotvSyncPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 match_id = 1;
  bool has_match_id() const;
  void clear_match_id();
  static const int kMatchIdFieldNumber = 1;
  ::google::protobuf::uint64 match_id() const;
  void set_match_id(::google::protobuf::uint64 value);

  // optional uint32 instance_id = 2;
  bool has_instance_id() const;
  void clear_instance_id();
  static const int kInstanceIdFieldNumber = 2;
  ::google::protobuf::uint32 instance_id() const;
  void set_instance_id(::google::protobuf::uint32 value);

  // optional uint32 signupfragment = 3;
  bool has_signupfragment() const;
  void clear_signupfragment();
  static const int kSignupfragmentFieldNumber = 3;
  ::google::protobuf::uint32 signupfragment() const;
  void set_signupfragment(::google::protobuf::uint32 value);

  // optional uint32 currentfragment = 4;
  bool has_currentfragment() const;
  void clear_currentfragment();
  static const int kCurrentfragmentFieldNumber = 4;
  ::google::protobuf::uint32 currentfragment() const;
  void set_currentfragment(::google::protobuf::uint32 value);

  // optional float tickrate = 5;
  bool has_tickrate() const;
  void clear_tickrate();
  static const int kTickrateFieldNumber = 5;
  float tickrate() const;
  void set_tickrate(float value);

  // optional uint32 tick = 6;
  bool has_tick() const;
  void clear_tick();
  static const int kTickFieldNumber = 6;
  ::google::protobuf::uint32 tick() const;
  void set_tick(::google::protobuf::uint32 value);

  // optional float rtdelay = 8;
  bool has_rtdelay() const;
  void clear_rtdelay();
  static const int kRtdelayFieldNumber = 8;
  float rtdelay() const;
  void set_rtdelay(float value);

  // optional float rcvage = 9;
  bool has_rcvage() const;
  void clear_rcvage();
  static const int kRcvageFieldNumber = 9;
  float rcvage() const;
  void set_rcvage(float value);

  // optional float keyframe_interval = 10;
  bool has_keyframe_interval() const;
  void clear_keyframe_interval();
  static const int kKeyframeIntervalFieldNumber = 10;
  float keyframe_interval() const;
  void set_keyframe_interval(float value);

  // optional uint32 cdndelay = 11;
  bool has_cdndelay() const;
  void clear_cdndelay();
  static const int kCdndelayFieldNumber = 11;
  ::google::protobuf::uint32 cdndelay() const;
  void set_cdndelay(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CEngineGotvSyncPacket)
 private:
  void set_has_match_id();
  void clear_has_match_id();
  void set_has_instance_id();
  void clear_has_instance_id();
  void set_has_signupfragment();
  void clear_has_signupfragment();
  void set_has_currentfragment();
  void clear_has_currentfragment();
  void set_has_tickrate();
  void clear_has_tickrate();
  void set_has_tick();
  void clear_has_tick();
  void set_has_rtdelay();
  void clear_has_rtdelay();
  void set_has_rcvage();
  void clear_has_rcvage();
  void set_has_keyframe_interval();
  void clear_has_keyframe_interval();
  void set_has_cdndelay();
  void clear_has_cdndelay();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 match_id_;
  ::google::protobuf::uint32 instance_id_;
  ::google::protobuf::uint32 signupfragment_;
  ::google::protobuf::uint32 currentfragment_;
  float tickrate_;
  ::google::protobuf::uint32 tick_;
  float rtdelay_;
  float rcvage_;
  float keyframe_interval_;
  ::google::protobuf::uint32 cdndelay_;
  friend struct  protobuf_engine_5fgcmessages_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CEngineGotvSyncPacket

// optional uint64 match_id = 1;
inline bool CEngineGotvSyncPacket::has_match_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_match_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CEngineGotvSyncPacket::clear_has_match_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CEngineGotvSyncPacket::clear_match_id() {
  match_id_ = GOOGLE_ULONGLONG(0);
  clear_has_match_id();
}
inline ::google::protobuf::uint64 CEngineGotvSyncPacket::match_id() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.match_id)
  return match_id_;
}
inline void CEngineGotvSyncPacket::set_match_id(::google::protobuf::uint64 value) {
  set_has_match_id();
  match_id_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.match_id)
}

// optional uint32 instance_id = 2;
inline bool CEngineGotvSyncPacket::has_instance_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_instance_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CEngineGotvSyncPacket::clear_has_instance_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CEngineGotvSyncPacket::clear_instance_id() {
  instance_id_ = 0u;
  clear_has_instance_id();
}
inline ::google::protobuf::uint32 CEngineGotvSyncPacket::instance_id() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.instance_id)
  return instance_id_;
}
inline void CEngineGotvSyncPacket::set_instance_id(::google::protobuf::uint32 value) {
  set_has_instance_id();
  instance_id_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.instance_id)
}

// optional uint32 signupfragment = 3;
inline bool CEngineGotvSyncPacket::has_signupfragment() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_signupfragment() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CEngineGotvSyncPacket::clear_has_signupfragment() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CEngineGotvSyncPacket::clear_signupfragment() {
  signupfragment_ = 0u;
  clear_has_signupfragment();
}
inline ::google::protobuf::uint32 CEngineGotvSyncPacket::signupfragment() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.signupfragment)
  return signupfragment_;
}
inline void CEngineGotvSyncPacket::set_signupfragment(::google::protobuf::uint32 value) {
  set_has_signupfragment();
  signupfragment_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.signupfragment)
}

// optional uint32 currentfragment = 4;
inline bool CEngineGotvSyncPacket::has_currentfragment() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_currentfragment() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CEngineGotvSyncPacket::clear_has_currentfragment() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CEngineGotvSyncPacket::clear_currentfragment() {
  currentfragment_ = 0u;
  clear_has_currentfragment();
}
inline ::google::protobuf::uint32 CEngineGotvSyncPacket::currentfragment() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.currentfragment)
  return currentfragment_;
}
inline void CEngineGotvSyncPacket::set_currentfragment(::google::protobuf::uint32 value) {
  set_has_currentfragment();
  currentfragment_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.currentfragment)
}

// optional float tickrate = 5;
inline bool CEngineGotvSyncPacket::has_tickrate() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_tickrate() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CEngineGotvSyncPacket::clear_has_tickrate() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CEngineGotvSyncPacket::clear_tickrate() {
  tickrate_ = 0;
  clear_has_tickrate();
}
inline float CEngineGotvSyncPacket::tickrate() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.tickrate)
  return tickrate_;
}
inline void CEngineGotvSyncPacket::set_tickrate(float value) {
  set_has_tickrate();
  tickrate_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.tickrate)
}

// optional uint32 tick = 6;
inline bool CEngineGotvSyncPacket::has_tick() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_tick() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CEngineGotvSyncPacket::clear_has_tick() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CEngineGotvSyncPacket::clear_tick() {
  tick_ = 0u;
  clear_has_tick();
}
inline ::google::protobuf::uint32 CEngineGotvSyncPacket::tick() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.tick)
  return tick_;
}
inline void CEngineGotvSyncPacket::set_tick(::google::protobuf::uint32 value) {
  set_has_tick();
  tick_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.tick)
}

// optional float rtdelay = 8;
inline bool CEngineGotvSyncPacket::has_rtdelay() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_rtdelay() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CEngineGotvSyncPacket::clear_has_rtdelay() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CEngineGotvSyncPacket::clear_rtdelay() {
  rtdelay_ = 0;
  clear_has_rtdelay();
}
inline float CEngineGotvSyncPacket::rtdelay() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.rtdelay)
  return rtdelay_;
}
inline void CEngineGotvSyncPacket::set_rtdelay(float value) {
  set_has_rtdelay();
  rtdelay_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.rtdelay)
}

// optional float rcvage = 9;
inline bool CEngineGotvSyncPacket::has_rcvage() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_rcvage() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CEngineGotvSyncPacket::clear_has_rcvage() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CEngineGotvSyncPacket::clear_rcvage() {
  rcvage_ = 0;
  clear_has_rcvage();
}
inline float CEngineGotvSyncPacket::rcvage() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.rcvage)
  return rcvage_;
}
inline void CEngineGotvSyncPacket::set_rcvage(float value) {
  set_has_rcvage();
  rcvage_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.rcvage)
}

// optional float keyframe_interval = 10;
inline bool CEngineGotvSyncPacket::has_keyframe_interval() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_keyframe_interval() {
  _has_bits_[0] |= 0x00000100u;
}
inline void CEngineGotvSyncPacket::clear_has_keyframe_interval() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void CEngineGotvSyncPacket::clear_keyframe_interval() {
  keyframe_interval_ = 0;
  clear_has_keyframe_interval();
}
inline float CEngineGotvSyncPacket::keyframe_interval() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.keyframe_interval)
  return keyframe_interval_;
}
inline void CEngineGotvSyncPacket::set_keyframe_interval(float value) {
  set_has_keyframe_interval();
  keyframe_interval_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.keyframe_interval)
}

// optional uint32 cdndelay = 11;
inline bool CEngineGotvSyncPacket::has_cdndelay() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CEngineGotvSyncPacket::set_has_cdndelay() {
  _has_bits_[0] |= 0x00000200u;
}
inline void CEngineGotvSyncPacket::clear_has_cdndelay() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void CEngineGotvSyncPacket::clear_cdndelay() {
  cdndelay_ = 0u;
  clear_has_cdndelay();
}
inline ::google::protobuf::uint32 CEngineGotvSyncPacket::cdndelay() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.cdndelay)
  return cdndelay_;
}
inline void CEngineGotvSyncPacket::set_cdndelay(::google::protobuf::uint32 value) {
  set_has_cdndelay();
  cdndelay_ = value;
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.cdndelay)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_engine_5fgcmessages_2eproto__INCLUDED
